--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/presentkim-pm/banner-factory
build-by-default: true
branches:
  - main
projects:
  banner-factory:
    model: virion
    type: library
    icon: assets/icon.png
    lint:
      phpstan: false
...
